// Stałe do obliczeń BAC (Widmark)
export const WIDMARK_CONSTANTS = {
  /** Water distribution coefficient for males */
  MALE_R: 0.68,
  /** Water distribution coefficient for females */
  FEMALE_R: 0.55,
  /** Average alcohol metabolism rate (grams per kg body weight per hour) */
  METABOLISM_RATE_PER_KG_PER_HOUR: 0.15,
  /** Ratio of threshold for "approaching" status (e.g. 0.9 = 90%) */
  APPROACHING_THRESHOLD_RATIO: 0.9,
} as const;
// Domyślny próg BAC (‰) dla nowych użytkowników
export const DEFAULT_THRESHOLD_BAC = 1.0;

// Minimalny próg BAC po blackout (‰)
export const BLACKOUT_MIN_THRESHOLD_BAC = 0.01;
// Error code constants for service and API error handling
export const ERROR_CODES = {
  PARTY_NOT_FOUND: "PARTY_NOT_FOUND",
  DATABASE_ERROR: "DATABASE_ERROR",
  FAILED_TO_LOG_EVENT: "FAILED_TO_LOG_EVENT",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PROFILE_INCOMPLETE: "PROFILE_INCOMPLETE",
  PARTY_ALREADY_ONGOING: "PARTY_ALREADY_ONGOING",
  PARTY_ALREADY_CLOSED: "PARTY_ALREADY_CLOSED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  CONFLICT: "CONFLICT",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NO_DRINKS_IN_PARTY: "NO_DRINKS_IN_PARTY",
  NO_THRESHOLD_FOUND: "NO_THRESHOLD_FOUND",
  CONSUMED_AT_BEFORE_PARTY_START: "CONSUMED_AT_BEFORE_PARTY_START",
  INVALID_ENDED_AT: "INVALID_ENDED_AT",
  CONSUMED_AT_AFTER_PARTY_END: "CONSUMED_AT_AFTER_PARTY_END",
  CONSUMED_AT_IN_FUTURE: "CONSUMED_AT_IN_FUTURE",
  UNREALISTIC_VOLUME: "UNREALISTIC_VOLUME",
  FAST_CONSUMPTION: "FAST_CONSUMPTION",
  BAC_LIMIT_EXCEEDED: "BAC_LIMIT_EXCEEDED",
  NO_BAC_CALCULATIONS: "NO_BAC_CALCULATIONS",
  DRINK_NOT_FOUND: "DRINK_NOT_FOUND",
  NOT_LAST_DRINK: "NOT_LAST_DRINK",
  VALIDATION_WARNINGS: "VALIDATION_WARNINGS",
};
